<!--Html layout for the footer of the page-->
<div id="footer">
    <div id="leftFoot" class="foot">
        <h4>Social</h4>
        <a href="https://github.com/MartiniDesignz" target="_blank"><i class="fa fa-github"></i></a>
        <a href="https://www.linkedin.com/in/robby-martini-72700a163/" target="_blank"><i class="fa fa-linkedin"></i></a>
    </div>
    <div id="centerFoot" class="foot">
        <h4>Info</h4>
        <p>MartiniDesignz <br> martinidesignz@gmail.com<br> Cincinnati, Ohio<br> USA</p>
    </div>
    <div id="rightFoot" class="foot">
        <h4>Credit</h4>
        <p style="font-size: 25px">Icons<br></p>
        <p>Generated by <a href="http://www.flaticon.com">flaticon.com</a></p>
        <p> <a style="text-decoration: underline" href="http://creativecommons.org/licenses/by/3.0/" target="_blank">Under CC:</a><br> 
            <a data-file="003-gear" href="http://www.freepik.com">Freepik</a>, 
            <a data-file="012-pc-computer-with-monitor" href="https://www.flaticon.com/authors/simpleicon" target="_blank">SimpleIcon</a>, 
            <a data-file="001-more-1" href="https://www.flaticon.com/authors/smashicons" target="_blank">Smashicons</a>, 
            <a data-file="009-console" href="https://www.flaticon.com/authors/good-ware" target="_blank">Good Ware</a>, 
            <a data-file="007-light-bulb-on" href="https://www.flaticon.com/authors/nice-and-serious" target="_blank">Nice and Serious</a>, 
            <a data-file="005-office" href="https://www.flaticon.com/authors/vectors-market" target="_blank">Vectors Market</a>, 
            <a data-file="006-computer" href="https://www.flaticon.com/authors/itim2101" target="_blank">itim2101</a>
        </p>  
    </div>
    <div id="btmSpacer" class="imgL"></div>
</div>